version: "3.9"
name: "backend-services"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodata:/data/mongodata

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/data/rabbitmqdata
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=example

  api:
    container_name: node_api
    restart: on-failure
    build: .
    volumes:
      - apidata:/app/src
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: >
      sh -c "yarn dev"
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodata:
  rabbitmqdata:
  apidata:
